### ISSUE TITLE
Conceptual: nullable X optional

### ISSUE THREAD

**Issue by marlon-sousa** [chubbyphp/chubbyphp-parsing#11]
Hello,

Specifically when parsing from json, there are two different situations which might need to be considered:

1. Key is not present. This, for javascript, would be translated to a key not present at all.
2. Value specifically set as null, as per JSON specification. This, in javascript, would be translated to a key with null value.

I have come to a point in which I am not sure about how to deal with this kind of validation.

I suppose nullable() means, in the sense of a schema, effectively an optional value: if it is present, it is parsed. If not present, it is ignored, meaning that an error is not thrown when parsing.

If this is the case, can we consider an optional() (like zod offers) for cases where the key might or not be present, meaning that the parsed object wouldn't have that key when parsed?

**Comment by dominikzogg** [comment]
@marlon-sousa it could be solved like that: https://github.com/chubbyphp/chubbyphp-parsing/pull/13/files

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-parsing/releases/tag/1.2.0
