### ISSUE TITLE
Exception message empty

### ISSUE THREAD

**Issue by marlon-sousa** [chubbyphp/chubbyphp-parsing#9]
Hello,

Great work!

I have only one problem: for me, the validator throws exceptions as expected, but the getMessage is always empty, meaning that we cannot log or present to the user what has caused the error.

I am using 1.0.1 as of now.

Is this behavior intended or would you accept help building these messages?

**Comment by dominikzogg** [comment]
Hi @marlon-sousa 

What would you expect from `getMessage` to happen for the `ParserErrorException`?
The idea would be to call `getApiProblemErrorMessages` to get the errors.

I could think of json_encode this content for `getMessage`.

Best, Dominik

**Comment by marlon-sousa** [comment]
Hello,

I am not kit sure because I am not a very fluent php programmer.

In most part of languages I have worked, the getMessage of the base exception class was always guaranteed to return a message describing the error.

I realized I probably got the wrong exception ... catch(Exception $e), but I need to better understand how a nom typed language such as php decides which exception is gotten when we perform a catch.

I inspected in the debugger the Exception $e instance variable and was not able to see a message describing what was wrong.

Perhaps the getApiProblemErrorMessages method was not made available for me because the (possible) casting to Exception?

Anywais, I think that a getMessage() method could provide a friendly explanation of what was wrong, letting for the user the decision to use getApiProblemErrorMessages if they want to format it differently.

**Comment by dominikzogg** [comment]
Hi @marlon-sousa

`getMessage` is meant to return something. I totally agree and forgot.

My Problem is, that the errors can be nested, so the message ca get rather long, and maybe not easy to understand.

It was meant to be used this way `catch (ParserErrorException $e) { $e->getApiProblemErrorMessages(); }` but i get your point.

Best,
Dominik

**Comment by marlon-sousa** [comment]
Perhaps then make the getMessage return a summary like:

Following fields are invalid:

a,
a/b,
b,
c/d/e

This way, again, one could just go with the summarized message via getMessage or call the more complete API to process the message by their selves.

**Comment by dominikzogg** [comment]
@marlon-sousa what do you think of this? https://github.com/chubbyphp/chubbyphp-parsing/pull/10/files

**Comment by marlon-sousa** [comment]
It seems ok.

Thanks!

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-parsing/releases/tag/1.1.2
